on:
  workflow_dispatch

# Store traffic data for more than 14 days

jobs:
  traffic:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: AR MultiPendulum traffic
      uses: sangonzal/repository-traffic-action@v0.1.4
      env:
        TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
    
    - name: Store AR MultiPendulum traffic
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
      with:
        source_file: './traffic/'
        destination_repo: ${{ secrets.TRAFFIC_DESTINATION }}
        destination_folder: ${{ secrets.AR_MULTIPENDULUM_TRAFFIC_FOLDER }}
        user_email: ${{ secrets.EMAIL }}
        user_name: ${{ secrets.USERNAME }}
